name: WP Smoketest

on:
  workflow_dispatch:

jobs:
  upload-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install reportlab
        run: pip install reportlab requests

      - name: Create dummy PDF
        run: |
          python - <<'PY'
          from reportlab.pdfgen import canvas
          from reportlab.lib.pagesizes import A4
          c = canvas.Canvas("/tmp/smoky.pdf", pagesize=A4)
          c.setFont("Helvetica-Bold", 20)
          c.drawString(100, 750, "Smoketest PDF Upload")
          c.save()
          PY

      - name: Upload to WordPress
        run: |
          curl -s -o response.json -w "%{http_code}" \
            -X POST "$WP_BASE_URL/wp-json/wp/v2/media" \
            -u "$WP_USER:$WP_APP_PASS" \
            -H "Content-Disposition: attachment; filename=smoky.pdf" \
            -H "Content-Type: application/pdf" \
            --data-binary @/tmp/smoky.pdf
          echo
          echo "=== WP Response ==="
          cat response.json
        env:
          WP_BASE_URL: ${{ secrets.WP_BASE_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASS: ${{ secrets.WP_APP_PASS }}
